### ISSUE TITLE
Error on custom element <hex-tab-list> & <hex-tab-panel-list>

### ISSUE THREAD

**Issue by jsblair9** [LionsMouthDigital/vue-hex-tabs#1]
Wasn't sure if I should log this here or on the Hex main project @curtisblackwell -- but I'm seeing the error on the Mastermind project. 

![error](https://cloud.githubusercontent.com/assets/4450975/14647305/c660767a-0622-11e6-8351-28e6bbf978cf.png)

**Comment by curtisblackwell** [comment]
The code just wasn't compiled.
